package se.devscout.server.api;

import se.devscout.android.util.concurrency.BackgroundTasksHandlerThread;
import se.devscout.android.util.http.UnauthorizedException;
import se.devscout.server.api.model.*;

import java.util.List;

public interface ActivityBank {

    Long DEFAULT_USER_ID = 1L; // <-- Must match the primary key id generated by SQLite when the database is initialized

    List<? extends Activity> findActivity(ActivityFilter condition) throws UnauthorizedException;

    Activity createActivity(ActivityProperties properties);

    void deleteActivity(ActivityKey key);

    ActivityProperties updateActivity(ActivityKey key, ActivityProperties properties);

    void readActivityAsync(ActivityKey key, OnReadDoneCallback<Activity> callback, BackgroundTasksHandlerThread tasksHandlerThread);

    List<? extends Activity> readActivities(ActivityKey... keys) throws UnauthorizedException;

    ActivityFilterFactory getFilterFactory();

    Reference createReference(ActivityKey key, ReferenceProperties properties);

    void deleteReference(ActivityKey key, ReferenceKey referenceKey);

    List<? extends Reference> readReferences(ActivityKey key);

    List<? extends Category> readCategories() throws UnauthorizedException;

    Category readCategoryFull(CategoryKey key);

    void setFavourite(ActivityKey activityKey, UserKey userKey);

    void unsetFavourite(ActivityKey activityKey, UserKey userKey);

    Boolean isFavourite(ActivityKey activityKey, UserKey userKey);

    List<? extends SearchHistory> readSearchHistory(int limit, UserKey userKey);

    SearchHistory createSearchHistory(HistoryProperties<SearchHistoryData> properties, UserKey userKey);

    void deleteSearchHistory(int itemsToKeep);

    void addListener(ActivityBankListener listener);

    void removeListener(ActivityBankListener listener);

    boolean createAnonymousAPIUser();

    Media readMediaItem(MediaKey key);
}
